version: "3.8"
services:
  database:
    image: mysql:8.0.25
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: task
